/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 pc.gltf
Author: Tobalation (https://sketchfab.com/tobalation)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/retro-computer-3a496376915846459d77fc14fdd6c1e0
Title: Retro computer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function PC(props) {
  const { nodes, materials } = useGLTF('/pc.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={4}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.TextureGrid} position={[0, 0, -0.03]} rotation={[0.09, 0, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.TextureGrid} position={[0, 0.5, 0.03]} rotation={[0.09, 0, 0]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.TextureGrid} position={[0.88, 0.06, 0.75]} rotation={[0.09, 0, 0]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.TextureGrid} position={[0, 0.06, 0.81]} rotation={[0.09, 0, 0]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/pc.gltf')


